feat: update v11 step 5 to React 18
carbon-design-system/carbon-tutorial pull request #10970
Opened 2023-06-27 14:47 UTC by alisonjoseph

Ref #https://github.com/carbon-design-system/carbon/issues/13630

#### Changelog

**New**

- Add react testing library

**Changed**

- Upgrade to React 18

**Removed**

- remove enzyme
- remove enzyme-adapter-react-16

**Note: Tests should fail, they will only pass after the user finishes step 5 and runs yarn build**

2023-06-27 15:40 UTC, francinelucca approved these changes

2023-06-29 14:32 UTC, tay1orjones approved these changes

2023-06-29 16:02 UTC, francinelucca requested changes
Having trouble running tests from this branch, I think maybe we need to mock `window.matchMedia`? 🤣
<img width="1212" alt="image" src="https://github.com/carbon-design-system/carbon-tutorial/assets/40550942/232bb346-8ef8-4a1a-9b32-047b2aefbf8b">

here's what we did on carbon: 
<img width="637" alt="image" src="https://github.com/carbon-design-system/carbon-tutorial/assets/40550942/095ac72f-51aa-4070-a4e0-646ad95c76fb">

2023-06-30 14:10 UTC, andreancardona approved these changes
Was also get the WatchMedia error :(

2023-07-05 17:09 UTC, francinelucca approved these changes
🚀

2023-07-05 17:33 UTC, andreancardona approved these changes

2023-07-05 17:35 UTC, merged